### ISSUE TITLE
[bug] Thumbnail sizing issue

### ISSUE THREAD

**Issue by LES-11** [Scratch-Client-4/itchy-ionic#60]
Thumbnails aren't sizing properly probably due to the image dimensions (this was tested on an android tablet if that helps)

![20220403_201831](https://user-images.githubusercontent.com/75516401/161677927-6349e383-37fe-4638-aaf8-ae92c9ac4b27.jpg)
![Screenshot_20220403-202200](https://user-images.githubusercontent.com/75516401/161677969-f0a38b4f-21b6-420e-bfbb-3fe9c05e8b71.jpg)

**Comment by locness3** [comment]
I believe this was fixed in #58 ?
> Fixed disproportionate scaling of project card thumbnails

**Comment by LES-11** [comment]
not sure if it was pushed to the play store yet when i tested it
i made these issues the same day i was testing
i was also testing on a tablet, not a phone so idk if scalling is different there
i can try again in the future ill also be testing landscape mode (if that is supported )

**Comment by micahlt** [comment]
I don't believe this has been pushed to Play yet - I'll try to get on making an update.

**Comment by micahlt** [comment]
@LES-11 Does the issue still exist on the latest version of Itchy from Google Play?

**Comment by LES-11** [comment]
> @LES-11 Does the issue still exist on the latest version of Itchy from Google Play?

@micahlt 
It seems to be fixed
